spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dlbh?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: MM-mysql666
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8088

jwt:
  #JWT储存请求头
  tokenHeader: Authorization
  #加载密使用的密钥
  secret: yeb-secret
  #超期限时间（60*60*24）
  expiration: 604800
  #负载中拿到开头
  tokenHead: Bearer
